// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Mozilla Campus Club of SLIIT",
            "url": "https://www.sliitmozilla.org/contact/",
            "email": "infosliitmcc@gmail.com"
        },
        "license": {
            "name": "MPL-2.0",
            "url": "https://github.com/Mozilla-Campus-Club-of-SLIIT/accounts/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/authorize": {
            "get": {
                "description": "Initiate the authentication flow with the auth service. Any external service should visit this route with a valid redirect\nIf the user is already logged in with the auth service, the auth service will redirect the user back to the provided url with a short lived temporary token (1 minute lifespan) - that should be used to complete the authentication",
                "tags": [
                    "Auth"
                ],
                "summary": "Initiate the authentication flow",
                "parameters": [
                    {
                        "type": "string",
                        "example": "http://localhost:3001/callback",
                        "description": "URL encoded redirect url",
                        "name": "redirect",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to the provided URL with temporary code in query param 'code'"
                    },
                    "400": {
                        "description": "Bad Request - invalid redirect URL"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/authorize/confirm": {
            "get": {
                "description": "Called after the user explicitly confirms a new/unrecognized redirect destination on the frontend confirmation page. Records consent for future silent redirects to the same host, then completes the authorization flow.",
                "tags": [
                    "Auth"
                ],
                "summary": "Confirm redirect and complete the authentication flow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL encoded redirect url",
                        "name": "redirect",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to the provided URL with temporary code in query param 'code'"
                    },
                    "400": {
                        "description": "Bad Request - invalid redirect URL"
                    },
                    "401": {
                        "description": "Not logged in"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/connections/github/": {
            "delete": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Unlink Github account from a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Connections"
                ],
                "summary": "Unlink Github account from a user",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Not logged in or invalid token"
                    },
                    "404": {
                        "description": "User or provider not found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/connections/github/callback": {
            "post": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Handles the OAuth authorization callback sent from Github\nThis endpoint is not meant to be invoked directly, but from Github once authorized from their platform\nSee more: [Github OAuth documentation](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Connections"
                ],
                "summary": "Handles the OAuth authorization callback sent from Github",
                "parameters": [
                    {
                        "type": "string",
                        "description": "([Github OAuth documentation](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps))",
                        "name": "state",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Set by Github OAuth. ([Github OAuth documentation](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps))",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to profile after successful linking"
                    },
                    "404": {
                        "description": "User or provider invalid (not found)"
                    },
                    "409": {
                        "description": "Already linked"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/connections/github/link": {
            "post": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Initiates the request to link an account with Github\nIf the user is logged in, redirect to Github OAuth authorization endpoint to initiate the Github browser authorization flow\nSee more: [Github OAuth documentation](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Connections"
                ],
                "summary": "Initiates the request to link an account with Github",
                "responses": {
                    "302": {
                        "description": "Redirect to Github OAuth authorization endpoint"
                    },
                    "401": {
                        "description": "Not logged in or invalid token"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Endpoint to log in a user with email and password\nUpon successful login user receives a pair of access token (found in response body) and refresh token (found in cookie: refreshToken)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Access token returned in response body; refresh token is set in cookie 'refreshToken'",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helpers.SuccessResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "token": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body"
                    },
                    "401": {
                        "description": "Invalid credentials"
                    },
                    "500": {
                        "description": "Internal Server error"
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "description": "Logout user. Clears the refreshToken cookie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout user",
                "responses": {
                    "200": {
                        "description": "Logout successful",
                        "schema": {
                            "$ref": "#/definitions/helpers.SuccessResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/roles": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Get all roles. Protected route",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "Get all roles",
                "responses": {
                    "200": {
                        "description": "Role list",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helpers.SuccessResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Not logged in or invalid token"
                    },
                    "403": {
                        "description": "Forbidden (admin only route)"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Create a new role. Protected route",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "Create a new role",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RoleModel"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Invalid request body"
                    },
                    "401": {
                        "description": "Not logged in or invalid token"
                    },
                    "403": {
                        "description": "Forbidden (admin only route)"
                    },
                    "409": {
                        "description": "Duplicate role"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/roles/{role}": {
            "delete": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Delete a role. Protected route",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "Delete a role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Role name",
                        "name": "role",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Not logged in or invalid token"
                    },
                    "403": {
                        "description": "Attempt to delete admin role"
                    },
                    "404": {
                        "description": "Role not found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Update a role. Protected route",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "Update a role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Role name",
                        "name": "role",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Name cannot be empty"
                    },
                    "401": {
                        "description": "Not logged in or invalid token"
                    },
                    "403": {
                        "description": "Attempt to modify admin role"
                    },
                    "404": {
                        "description": "Role not found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/session": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Get the current session using the access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get current session",
                "responses": {
                    "200": {
                        "description": "Session data",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helpers.SuccessResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "id": {
                                                    "type": "string"
                                                },
                                                "roles": {
                                                    "type": "array",
                                                    "items": {
                                                        "type": "string"
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Not logged in or invalid token"
                    },
                    "500": {
                        "description": "Internal Server error"
                    }
                }
            }
        },
        "/token": {
            "post": {
                "description": "This is the second step of the authorization flow Check GET /api/authorize for more information about the first step of this flow.\nThe client should invoke this endpoint with the code received from the previous step.\nThe client shall receive a pair of access token (found in response body) and refresh token (found in cookie: refreshToken) after completing all the steps.\nClient can act on behalf of the user after receiving the token pair",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get tokens from code",
                "parameters": [
                    {
                        "type": "string",
                        "example": "abcdefgh",
                        "description": "URL encoded code received from previous step",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Access token returned in response body; refresh token is set in cookie 'refreshToken'",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helpers.SuccessResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "token": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "If token is invalid or expired"
                    },
                    "404": {
                        "description": "Token is related to a non-existing user"
                    },
                    "500": {
                        "description": "Internal Server error"
                    }
                }
            }
        },
        "/token/refresh": {
            "post": {
                "description": "Refresh the access token with the refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh acess token",
                "responses": {
                    "200": {
                        "description": "Access token",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helpers.SuccessResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "token": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Invalid or missing refresh token"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "List all users. Admin only route",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "List all users",
                "responses": {
                    "200": {
                        "description": "User list",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helpers.SuccessResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.UserModel"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Not logged in or invalid token"
                    },
                    "403": {
                        "description": "Forbidden (admin only route)"
                    }
                }
            },
            "post": {
                "description": "Create user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.createUserBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Invalid request body"
                    },
                    "409": {
                        "description": "Username or email already in use"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Get current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "Current user",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helpers.SuccessResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.UserModel"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "User not found. This error can only happen if the user is deleted while invoking this endpoint"
                    },
                    "401": {
                        "description": "Not logged in or invalid token"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Update current user details such as username, social links, etc.\nEndpoint not implemented yet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update current user",
                "responses": {
                    "401": {
                        "description": "Not logged in or invalid token"
                    },
                    "500": {
                        "description": "Internal Server error"
                    }
                }
            }
        },
        "/users/me/password": {
            "patch": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Change password of current user\nEndpoint not implemented yet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Change password of current user",
                "responses": {
                    "401": {
                        "description": "Not logged in or invalid token"
                    },
                    "500": {
                        "description": "Internal Server error"
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Get a specific user\nIf the user has set the profile visibility as public then it is free to view by anyone. If the profile is set to be private, then regular users will not gain the access to this resource.\nHowever, admin users can still bypass this protection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get a specific user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helpers.SuccessResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.UserModel"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid user id"
                    },
                    "401": {
                        "description": "Not logged in or invalid token"
                    },
                    "403": {
                        "description": "Forbidden. Trying to access another user's account. Admins can bypass this"
                    },
                    "404": {
                        "description": "User not found"
                    },
                    "500": {
                        "description": "Internal Server error"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Delete a user. Admin only route",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Invalid user id"
                    },
                    "401": {
                        "description": "Not logged in or invalid token"
                    },
                    "403": {
                        "description": "Cannot delete yourself"
                    },
                    "404": {
                        "description": "User not found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Update a user. Admin only route\nNot implemented yet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update a user",
                "responses": {
                    "401": {
                        "description": "Not logged in or invalid token"
                    },
                    "403": {
                        "description": "Forbidden (admin only route)"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/users/{id}/roles": {
            "post": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Add a role to the user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Add a role to the user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RoleModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Role cannot be empty"
                    },
                    "401": {
                        "description": "Not logged in or invalid token"
                    },
                    "403": {
                        "description": "Forbidden (admin only route)"
                    },
                    "404": {
                        "description": "User or role not found"
                    },
                    "409": {
                        "description": "Already assigned"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/users/{id}/roles/{role}": {
            "delete": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Remove an existing role from the user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Remove an existing role from the user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Role name",
                        "name": "role",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Invalid user id"
                    },
                    "401": {
                        "description": "Not logged in or invalid token"
                    },
                    "403": {
                        "description": "Cannot remove admin from yourself"
                    },
                    "404": {
                        "description": "User or role not found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.LoginRequestBody": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "infosliitmcc@gmail.com"
                },
                "password": {
                    "type": "string",
                    "example": "password"
                }
            }
        },
        "handlers.createUserBody": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 50,
                    "example": "infosliitmcc@gmail.com"
                },
                "name": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 3,
                    "example": "sliitmozillian"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "password"
                }
            }
        },
        "helpers.SuccessResponseModel": {
            "type": "object",
            "properties": {
                "data": {}
            }
        },
        "models.ConnectionModel": {
            "type": "object",
            "properties": {
                "linkedAt": {
                    "type": "string",
                    "example": "2025-12-31T00:00:00Z"
                },
                "provider": {
                    "type": "string",
                    "example": "github"
                },
                "providerAccountEmail": {
                    "type": "string",
                    "example": "infosliitmcc@gmail.com"
                },
                "providerUserId": {
                    "type": "string",
                    "example": "1"
                },
                "providerUserName": {
                    "type": "string",
                    "example": "sliitmozillian"
                }
            }
        },
        "models.RoleModel": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "models.UserModel": {
            "type": "object",
            "properties": {
                "connections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ConnectionModel"
                    }
                },
                "createdAt": {
                    "type": "string",
                    "example": "2025-12-31T00:00:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "infosliitmcc@gmail.com"
                },
                "id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "name": {
                    "type": "string",
                    "example": "sliitmozillian"
                },
                "password": {
                    "type": "string"
                },
                "private": {
                    "type": "boolean"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "admin"
                    ]
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2025-12-31T00:00:00Z"
                }
            }
        }
    },
    "securityDefinitions": {
        "AccessToken": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "accounts.sliitmozilla.org",
	BasePath:         "/api",
	Schemes:          []string{"https", "http"},
	Title:            "sliitmozilla Auth Service",
	Description:      "API documentation for the authentication service used across all SLIITMozilla.\nWe use `helpers.SuccessResponseModel` for successful responses and `helpers.FailureResponseModel` for errors.\nExample success response:\n```json\n{ \"data\": ... }\n```\nExample failure response:\n```json\n{ \"error\": { \"code\": 500, \"message\": ... }}\n```",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
